# Generated by Django 5.2.17 on 2026-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginotpchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotpchallenge',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=16),
        ),
    ]
