# Generated by Django 5.2.17 on 2026-08-20 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('service_areas', models.ManyToManyField(blank=True, related_name='technicians', to='locations.servicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='technicians', to='technicians.technicianskill')),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='TechnicianAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_assignments', to='bookings.booking')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='technicians.technicianprofile')),
            ],
            options={
                'ordering': ('-assigned_at',),
                'indexes': [models.Index(fields=['booking', 'assigned_at'], name='technicians_booking_caaf37_idx'), models.Index(fields=['technician', 'unassigned_at'], name='technicians_technic_dc0b09_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['employee_code'], name='technicians_employe_aa9327_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['is_active', 'is_available'], name='technicians_is_acti_59dc81_idx'),
        ),
    ]
