# Generated by Django 5.2.17 on 2026-08-29 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_existing_active_technicians_verified(apps, schema_editor):
    TechnicianProfile = apps.get_model('technicians', 'TechnicianProfile')
    TechnicianProfile.objects.filter(is_active=True).update(background_verification_status='VERIFIED')


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalogue', '0002_serviceimage_alter_service_options_and_more'),
        ('locations', '0001_initial'),
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianLeave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='TechnicianWorkingHours',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('technician', 'day_of_week', 'start_time'),
            },
        ),
        migrations.AddField(
            model_name='technicianassignment',
            name='notification_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='technicianassignment',
            name='previous_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_assignments', to='technicians.technicianprofile'),
        ),
        migrations.AddField(
            model_name='technicianassignment',
            name='reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='address_proof_document',
            field=models.FileField(blank=True, upload_to='technicians/address-proofs/'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_LEAVE', 'On leave'), ('OFFLINE', 'Offline'), ('SUSPENDED', 'Suspended')], default='AVAILABLE', max_length=24),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='background_verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=24),
        ),
        migrations.RunPython(mark_existing_active_technicians_verified, migrations.RunPython.noop),
        migrations.AddField(
            model_name='technicianprofile',
            name='cancellation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='completed_job_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LEFT', 'Left')], default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='experience_years',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='id_proof_document',
            field=models.FileField(blank=True, upload_to='technicians/id-proofs/'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='id_proof_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='technicians/photos/'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='supported_services',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='catalogue.service'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='technician_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CONTRACT', 'Contract technician'), ('PARTNER', 'Service partner')], default='EMPLOYEE', max_length=24),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['phone'], name='technicians_phone_8c8cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['city', 'pincode'], name='technicians_city_67761b_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['background_verification_status', 'availability_status'], name='technicians_backgro_e8a6d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicianassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('booking',), name='unique_active_assignment_per_booking'),
        ),
        migrations.AddField(
            model_name='technicianleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_leaves_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianleave',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='technicians.technicianprofile'),
        ),
        migrations.AddField(
            model_name='technicianworkinghours',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='technicians.technicianprofile'),
        ),
        migrations.AddIndex(
            model_name='technicianleave',
            index=models.Index(fields=['technician', 'is_active', 'start_at', 'end_at'], name='technicians_technic_6d4214_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicianworkinghours',
            constraint=models.UniqueConstraint(fields=('technician', 'day_of_week', 'start_time', 'end_time'), name='unique_technician_working_window'),
        ),
    ]
