# Generated by Django 5.2.17 on 2026-09-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_technicianleave_technicianworkinghours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianleave',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
