from decimal import Decimal

from django.core.management.base import BaseCommand

from apps.catalogue.models import Service, ServiceCategory
from apps.locations.models import ServiceArea


class Command(BaseCommand):
    help = "Seed development service categories and Purple Squad services."

    def handle(self, *args, **options):
        category_data = [
            {
                "name": "Home Appliances Repair",
                "slug": "home-appliances-repair",
                "description": "Repair, servicing, installation, and maintenance for essential home appliances.",
                "display_order": 1,
            },
            {
                "name": "Cleaning",
                "slug": "cleaning",
                "description": "Home, bathroom, tank, and chimney cleaning services for healthier spaces.",
                "display_order": 2,
            },
            {
                "name": "Home Maintenance",
                "slug": "home-maintenance",
                "description": "Mosquito net, sofa repair, and other home maintenance visits.",
                "display_order": 3,
            },
        ]
        categories = {}
        for item in category_data:
            category, _ = ServiceCategory.objects.update_or_create(
                slug=item["slug"],
                defaults={
                    "name": item["name"],
                    "description": item["description"],
                    "display_order": item["display_order"],
                    "is_active": True,
                },
            )
            categories[item["slug"]] = category

        included_repair = "Technician visit\nIssue diagnosis\nBasic external inspection\nService estimate before extra work"
        excluded_repair = "Spare parts\nMajor component replacement\nCivil, plumbing, or electrical line work\nBrand warranty handling"
        repair_note = "Final repair cost depends on appliance condition and required parts. Technician confirms extra charges before work starts."

        service_data = [
            {
                "category": "home-appliances-repair",
                "name": "AC Service",
                "slug": "ac-service",
                "short_description": "AC cleaning, cooling check, and routine maintenance for better airflow.",
                "description": "A professional AC service visit for split or window AC units. The technician cleans accessible parts, checks airflow, reviews drainage, and identifies repair or gas-refill needs if present.",
                "whats_included": "Filter cleaning\nIndoor unit inspection\nOutdoor unit visual check\nDrainage check\nBasic cooling test",
                "whats_excluded": "Gas refill\nSpare parts\nDeep jet cleaning\nCompressor, PCB, or motor repair",
                "important_notes": "Power and safe access to indoor and outdoor units are required.",
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("499.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 1,
            },
            {
                "category": "home-appliances-repair",
                "name": "Washing Machine Repair & Service",
                "slug": "washing-machine-repair-service",
                "short_description": "Diagnosis and service for washing, spinning, draining, and noise issues.",
                "description": "Service for semi-automatic, top-load, and front-load washing machines with problems such as water not draining, drum noise, vibration, or cycle failure.",
                "whats_included": included_repair,
                "whats_excluded": excluded_repair,
                "important_notes": repair_note,
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 2,
            },
            {
                "category": "home-appliances-repair",
                "name": "Refrigerator Repair & Services",
                "slug": "refrigerator-repair-services",
                "short_description": "Cooling, leakage, noise, and compressor-related refrigerator inspection.",
                "description": "Technician diagnosis for refrigerators that are not cooling, over-cooling, leaking water, making noise, or showing electrical faults.",
                "whats_included": included_repair,
                "whats_excluded": excluded_repair,
                "important_notes": repair_note,
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("499.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 3,
            },
            {
                "category": "home-appliances-repair",
                "name": "TV Repair & Services",
                "slug": "tv-repair-services",
                "short_description": "TV display, sound, power, and connectivity issue diagnosis.",
                "description": "Inspection and service estimate for LED, LCD, and smart TVs facing no display, no sound, power, remote, or input issues.",
                "whats_included": included_repair,
                "whats_excluded": "Panel replacement\nMotherboard or speaker parts\nWall mount bracket\nBrand warranty handling",
                "important_notes": repair_note,
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": True,
                "display_order": 4,
            },
            {
                "category": "home-appliances-repair",
                "name": "Geyser Repair & Services",
                "slug": "geyser-repair-services",
                "short_description": "Geyser heating, leakage, wiring, thermostat, and servicing support.",
                "description": "Technician visit for electric geyser problems such as no heating, slow heating, leakage, tripping, or unusual noise.",
                "whats_included": included_repair,
                "whats_excluded": "Heating element or thermostat parts\nPlumbing changes\nWall drilling\nElectrical line repair",
                "important_notes": "Water and power supply must be available for testing.",
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": False,
                "display_order": 5,
            },
            {
                "category": "home-appliances-repair",
                "name": "Water Purifier Repair & Services",
                "slug": "water-purifier-repair-services",
                "short_description": "RO/UV purifier service for leakage, low flow, taste, and filter issues.",
                "description": "Repair and maintenance visit for water purifiers with slow water flow, leakage, bad taste, filter alerts, or power issues.",
                "whats_included": included_repair,
                "whats_excluded": "Filters, membrane, pump, UV lamp, or other parts\nPlumbing changes\nWater quality lab testing",
                "important_notes": "Filter or membrane replacement is quoted separately after inspection.",
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": True,
                "display_order": 6,
            },
            {
                "category": "home-appliances-repair",
                "name": "Microwave Oven Repair & Services",
                "slug": "microwave-oven-repair-services",
                "short_description": "Microwave heating, plate rotation, spark, and power issue diagnosis.",
                "description": "Technician visit for microwave ovens with heating failure, turntable issues, sparking, buttons not working, or power faults.",
                "whats_included": included_repair,
                "whats_excluded": "Magnetron, diode, capacitor, fuse, panel, or door parts\nInternal deep cleaning",
                "important_notes": repair_note,
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": False,
                "display_order": 7,
            },
            {
                "category": "home-appliances-repair",
                "name": "Dishwasher Repair & Service",
                "slug": "dishwasher-repair-service",
                "short_description": "Dishwasher drainage, cleaning, water inlet, and noise issue diagnosis.",
                "description": "Service visit for dishwashers with poor cleaning, water not draining, water inlet errors, unusual noise, or cycle interruptions.",
                "whats_included": included_repair,
                "whats_excluded": "Pump, motor, sensor, spray arm, or control-board parts\nPlumbing or cabinet modifications",
                "important_notes": repair_note,
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("549.00"),
                "advance_amount": Decimal("199.00"),
                "estimated_duration_minutes": 75,
                "is_featured": False,
                "is_popular": False,
                "display_order": 8,
            },
            {
                "category": "home-appliances-repair",
                "name": "TV Wall Mount Installation",
                "slug": "tv-wall-mount-installation",
                "short_description": "Secure TV wall mounting with alignment and basic setup.",
                "description": "Installation service for mounting a TV on a suitable wall, aligning the bracket, and checking viewing position and cable access.",
                "whats_included": "Wall mount installation\nTV mounting and alignment\nBasic safety check\nCable position guidance",
                "whats_excluded": "Wall mount bracket\nConcealed wiring\nElectrical socket work\nCivil repair or reinforcement",
                "important_notes": "Customer should provide a compatible wall mount bracket unless arranged separately.",
                "base_price": Decimal("799.00"),
                "selling_price": Decimal("599.00"),
                "advance_amount": Decimal("199.00"),
                "estimated_duration_minutes": 75,
                "is_featured": False,
                "is_popular": True,
                "display_order": 9,
            },
            {
                "category": "home-appliances-repair",
                "name": "CCTV Cameras Repair and Installation",
                "slug": "cctv-cameras-repair-installation",
                "short_description": "CCTV camera setup, connection checks, and repair inspection.",
                "description": "Technician visit for CCTV installation or troubleshooting camera, DVR/NVR, power, display, or cable connectivity issues.",
                "whats_included": "Camera point inspection\nBasic installation or repair estimate\nDVR/NVR connection check\nLive-view guidance",
                "whats_excluded": "Cameras, DVR/NVR, hard disk, cable, adapter, or networking equipment\nHigh-ladder or concealed wiring work",
                "important_notes": "Final cost depends on number of camera points and material required.",
                "base_price": Decimal("999.00"),
                "selling_price": Decimal("799.00"),
                "advance_amount": Decimal("249.00"),
                "estimated_duration_minutes": 90,
                "is_featured": False,
                "is_popular": False,
                "display_order": 10,
            },
            {
                "category": "cleaning",
                "name": "Chimney Cleaning & Services",
                "slug": "chimney-cleaning-services",
                "short_description": "Kitchen chimney filter, hood, and grease cleaning service.",
                "description": "Cleaning service for kitchen chimneys affected by grease, smoke residue, and reduced suction. Helps improve airflow and kitchen hygiene.",
                "whats_included": "Filter cleaning\nHood surface cleaning\nAccessible grease removal\nBasic suction check",
                "whats_excluded": "Motor repair\nDuct replacement\nSpare parts\nDeep duct dismantling",
                "important_notes": "Heavy grease buildup may need additional time or repeat cleaning.",
                "base_price": Decimal("899.00"),
                "selling_price": Decimal("699.00"),
                "advance_amount": Decimal("199.00"),
                "estimated_duration_minutes": 75,
                "is_featured": True,
                "is_popular": True,
                "display_order": 1,
            },
            {
                "category": "cleaning",
                "name": "Full House Cleaning",
                "slug": "full-house-cleaning",
                "short_description": "Complete home cleaning for floors, surfaces, rooms, and common areas.",
                "description": "A full-house cleaning visit for occupied homes that need deep dusting, floor cleaning, bathroom touch-up, kitchen surface cleaning, and room-wise hygiene care.",
                "whats_included": "Room dusting\nFloor cleaning\nKitchen exterior surface cleaning\nBathroom touch-up\nCommon area cleaning",
                "whats_excluded": "Pest control\nInterior cabinet cleaning\nSofa or mattress shampooing\nPaint or renovation cleanup",
                "important_notes": "Exact scope and duration depend on home size and condition.",
                "base_price": Decimal("2499.00"),
                "selling_price": Decimal("1999.00"),
                "advance_amount": Decimal("499.00"),
                "estimated_duration_minutes": 240,
                "is_featured": True,
                "is_popular": True,
                "display_order": 2,
            },
            {
                "category": "cleaning",
                "name": "Bathroom Cleaning",
                "slug": "bathroom-cleaning",
                "short_description": "Bathroom tile, floor, mirror, tap, and fixture cleaning.",
                "description": "Bathroom cleaning service focused on stains, scale, floor dirt, mirror marks, fixture buildup, and overall freshness.",
                "whats_included": "Floor and wall tile cleaning\nTap and fixture cleaning\nMirror cleaning\nCommode and basin cleaning\nBasic deodorizing",
                "whats_excluded": "Plumbing repair\nGrout replacement\nSevere hard-water restoration\nPest control",
                "important_notes": "Very old stains may lighten but may not disappear completely in one visit.",
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("499.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 3,
            },
            {
                "category": "cleaning",
                "name": "Water Tank Cleaning",
                "slug": "water-tank-cleaning",
                "short_description": "Overhead or sump tank cleaning for sediment and hygiene buildup.",
                "description": "Water tank cleaning service to remove settled dirt, slime, and visible buildup from accessible domestic water tanks.",
                "whats_included": "Tank draining support\nManual scrubbing\nSludge removal\nRinse and basic hygiene check",
                "whats_excluded": "Tank repair\nPlumbing repair\nChemical treatment beyond standard cleaning\nHigh-risk access work",
                "important_notes": "Customer must provide safe tank access and water/power availability.",
                "base_price": Decimal("1299.00"),
                "selling_price": Decimal("999.00"),
                "advance_amount": Decimal("249.00"),
                "estimated_duration_minutes": 120,
                "is_featured": False,
                "is_popular": True,
                "display_order": 4,
            },
        ]

        service_data.extend(
            [
                {
                    "category": "home-appliances-repair",
                    "name": "AC Inspection Charge",
                    "slug": "ac-inspection-charge",
                    "short_description": "Technician visit to inspect AC cooling, airflow, power, leakage, or noise issues.",
                    "description": "AC inspection visit for split or window AC units. The technician diagnoses the issue and confirms the repair estimate before extra work starts.",
                    "whats_included": "Technician visit\nCooling check\nAirflow check\nDrainage and leakage inspection\nRepair estimate",
                    "whats_excluded": "Spare parts\nGas refill\nDeep cleaning\nInstallation or uninstallation",
                    "important_notes": repair_note,
                    "base_price": Decimal("299.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 45,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 11,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "AC Installation",
                    "slug": "ac-installation",
                    "short_description": "Standard split AC installation with fitting, mounting, and basic performance check.",
                    "description": "Standard AC installation service with indoor and outdoor unit placement, pipe connection, drain setup, and basic cooling check.",
                    "whats_included": "Indoor unit mounting\nOutdoor unit placement guidance\nCopper pipe connection check\nDrain pipe setup\nBasic cooling test",
                    "whats_excluded": "Stand, bracket, copper pipe, drain pipe, wiring, stabilizer, core cutting, or civil work",
                    "important_notes": "Material and extra installation work are quoted separately before work starts.",
                    "base_price": Decimal("1899.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 150,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 12,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "AC Uninstallation",
                    "slug": "ac-uninstallation",
                    "short_description": "Safe AC removal with gas lock, unit removal, and basic packing guidance.",
                    "description": "AC uninstallation service for shifting or replacement, including safe unit removal and basic handover.",
                    "whats_included": "Gas lock where possible\nIndoor unit removal\nOutdoor unit removal\nPipe disconnection\nBasic handover",
                    "whats_excluded": "Transport\nWall repair\nNew installation\nReplacement materials",
                    "important_notes": "Safe access to indoor and outdoor units is required.",
                    "base_price": Decimal("999.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 90,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 13,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "AC Repair & Gas Refill",
                    "slug": "ac-repair-gas-refill",
                    "short_description": "AC repair visit with gas refill package after leakage and cooling diagnosis.",
                    "description": "AC repair and gas refill package for low cooling or gas leakage symptoms. Technician confirms suitability after inspection.",
                    "whats_included": "Cooling diagnosis\nLeakage check guidance\nGas refill\nBasic performance check",
                    "whats_excluded": "Major leak repair\nCopper pipe replacement\nCompressor, PCB, motor, or other parts",
                    "important_notes": repair_note,
                    "base_price": Decimal("2799.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 120,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 14,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "Foam Jet AC Service",
                    "slug": "foam-jet-ac-service",
                    "short_description": "Foam jet cleaning service for AC filters, coil surface, and accessible parts.",
                    "description": "Foam jet AC service for better airflow and routine hygiene cleaning of accessible indoor unit parts.",
                    "whats_included": "Filter cleaning\nFoam jet cleaning of accessible coil surface\nDrainage check\nCooling test",
                    "whats_excluded": "Gas refill\nSpare parts\nOutdoor unit deep wash\nMajor repair",
                    "important_notes": "Power and safe access are required during service.",
                    "base_price": Decimal("999.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 75,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 15,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "Full AC Chemical Wash",
                    "slug": "full-ac-chemical-wash",
                    "short_description": "Deep AC chemical wash for indoor unit cleaning and better cooling performance.",
                    "description": "Deep chemical wash for AC units with heavy dust or reduced airflow, including careful cleaning of accessible parts.",
                    "whats_included": "Indoor unit chemical cleaning\nFilter wash\nDrain tray cleaning\nDrainage check\nCooling test",
                    "whats_excluded": "Gas refill\nSpare parts\nMajor repair\nCivil or electrical work",
                    "important_notes": "Technician will confirm if chemical wash is suitable after inspection.",
                    "base_price": Decimal("2499.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 120,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 16,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "AC Uninstallation & Installation",
                    "slug": "ac-uninstallation-installation",
                    "short_description": "Combo package for removing an existing AC and installing it at another location.",
                    "description": "AC shifting combo for uninstallation and installation with basic fitting and performance check.",
                    "whats_included": "AC uninstallation\nAC installation\nDrainage setup\nBasic cooling test",
                    "whats_excluded": "Transport\nExtra copper pipe, wire, stand, bracket, core cutting, or civil work",
                    "important_notes": "Material and transport charges are confirmed separately.",
                    "base_price": Decimal("2700.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 240,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 17,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "AC Installation & Full AC Chemical Wash",
                    "slug": "ac-installation-full-ac-chemical-wash",
                    "short_description": "Combo package for AC installation with full chemical wash.",
                    "description": "AC installation plus full chemical wash package for customers shifting or refreshing an existing unit.",
                    "whats_included": "Standard AC installation\nIndoor unit chemical wash\nDrainage check\nCooling test",
                    "whats_excluded": "Transport\nGas refill\nSpare parts\nExtra installation materials",
                    "important_notes": "Technician confirms extra materials before work starts.",
                    "base_price": Decimal("4099.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 240,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 18,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "Geyser Installation",
                    "slug": "geyser-installation",
                    "short_description": "Geyser installation with mounting, connection check, and basic testing.",
                    "description": "Geyser installation service for suitable bathroom or utility wall points.",
                    "whats_included": "Mounting guidance\nConnection check\nBasic testing\nSafety guidance",
                    "whats_excluded": "Plumbing materials\nElectrical wiring\nWall drilling beyond standard fitting\nOld unit removal",
                    "important_notes": "Customer must provide compatible installation point and required materials.",
                    "base_price": Decimal("500.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 75,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 19,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "TV Wall Mount - Up to 26 inch",
                    "slug": "tv-wall-mount-up-to-26-inch",
                    "short_description": "TV wall mount installation for screens up to 26 inches.",
                    "description": "Wall mounting service for small TVs with alignment and basic safety check.",
                    "whats_included": "Wall mount fitting\nTV placement and alignment\nBasic safety check",
                    "whats_excluded": "Bracket\nConcealed wiring\nElectrical or civil work",
                    "important_notes": "Customer should provide a compatible bracket.",
                    "base_price": Decimal("399.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 60,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 20,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "TV Wall Mount - 32 to 43 inch",
                    "slug": "tv-wall-mount-32-to-43-inch",
                    "short_description": "TV wall mount installation for 32 to 43 inch screens.",
                    "description": "Wall mounting service for medium TVs with bracket alignment and safe placement.",
                    "whats_included": "Wall mount fitting\nTV placement and alignment\nBasic safety check",
                    "whats_excluded": "Bracket\nConcealed wiring\nElectrical or civil work",
                    "important_notes": "Customer should provide a compatible bracket.",
                    "base_price": Decimal("599.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 75,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 21,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "TV Wall Mount - 46 to 55 inch",
                    "slug": "tv-wall-mount-46-to-55-inch",
                    "short_description": "TV wall mount installation for 46 to 55 inch screens.",
                    "description": "Wall mounting service for large TVs with positioning and alignment support.",
                    "whats_included": "Wall mount fitting\nTV placement and alignment\nBasic safety check",
                    "whats_excluded": "Bracket\nConcealed wiring\nElectrical or civil work",
                    "important_notes": "Customer should provide a compatible bracket.",
                    "base_price": Decimal("699.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 90,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 22,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "TV Wall Mount - 56 to 65 inch",
                    "slug": "tv-wall-mount-56-to-65-inch",
                    "short_description": "TV wall mount installation for 56 to 65 inch screens.",
                    "description": "Wall mounting service for extra-large TVs with careful alignment and safety check.",
                    "whats_included": "Wall mount fitting\nTV placement and alignment\nBasic safety check",
                    "whats_excluded": "Bracket\nConcealed wiring\nElectrical or civil work",
                    "important_notes": "Customer should provide a compatible bracket and safe wall surface.",
                    "base_price": Decimal("899.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 105,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 23,
                },
                {
                    "category": "home-appliances-repair",
                    "name": "TV Wall Mount - Over 75 inch",
                    "slug": "tv-wall-mount-over-75-inch",
                    "short_description": "TV wall mount installation for premium large-screen TVs over 75 inches.",
                    "description": "Specialist wall mount visit for very large TVs with alignment and safety guidance.",
                    "whats_included": "Wall mount fitting\nTV placement and alignment\nBasic safety check",
                    "whats_excluded": "Bracket\nConcealed wiring\nElectrical or civil work\nAdditional helper charges if required",
                    "important_notes": "Site feasibility will be confirmed before installation.",
                    "base_price": Decimal("1899.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 150,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 24,
                },
                {
                    "category": "cleaning",
                    "name": "Deep Cleaning - Wall-mount Chimney",
                    "slug": "deep-cleaning-wall-mount-chimney",
                    "short_description": "Deep grease cleaning for wall-mount kitchen chimney.",
                    "description": "Deep cleaning package for wall-mount chimneys with heavy oil and grease buildup.",
                    "whats_included": "Filter cleaning\nHood cleaning\nAccessible grease removal\nBasic suction check",
                    "whats_excluded": "Motor repair\nDuct replacement\nSpare parts",
                    "important_notes": "Heavy buildup may require additional time.",
                    "base_price": Decimal("1199.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 90,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 25,
                },
                {
                    "category": "cleaning",
                    "name": "Deep Cleaning - Island Chimney",
                    "slug": "deep-cleaning-island-chimney",
                    "short_description": "Deep grease cleaning for island kitchen chimney.",
                    "description": "Deep cleaning package for island chimneys with filter, hood, and accessible grease cleaning.",
                    "whats_included": "Filter cleaning\nHood cleaning\nAccessible grease removal\nBasic suction check",
                    "whats_excluded": "Motor repair\nDuct replacement\nSpare parts",
                    "important_notes": "Safe ladder access is required.",
                    "base_price": Decimal("1499.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 120,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 26,
                },
                {
                    "category": "cleaning",
                    "name": "Chimney Installation - Wall-mount Chimney",
                    "slug": "chimney-installation-wall-mount-chimney",
                    "short_description": "Installation service for wall-mount kitchen chimney.",
                    "description": "Wall-mount chimney installation with fitting and basic operating check.",
                    "whats_included": "Chimney mounting\nAlignment\nBasic operating check",
                    "whats_excluded": "Duct, clamp, wiring, drilling beyond standard fitting, or civil work",
                    "important_notes": "Customer must provide compatible chimney and installation materials.",
                    "base_price": Decimal("699.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 90,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 27,
                },
                {
                    "category": "cleaning",
                    "name": "Chimney Installation - Island Chimney",
                    "slug": "chimney-installation-island-chimney",
                    "short_description": "Installation service for island kitchen chimney.",
                    "description": "Island chimney installation with alignment, mounting, and basic operating check.",
                    "whats_included": "Chimney mounting\nAlignment\nBasic operating check",
                    "whats_excluded": "Duct, clamp, wiring, drilling beyond standard fitting, or civil work",
                    "important_notes": "Site feasibility is confirmed before installation.",
                    "base_price": Decimal("1499.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 150,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 28,
                },
                {
                    "category": "cleaning",
                    "name": "Overhead Water Tank Cleaning - Up to 1000 Litres",
                    "slug": "overhead-water-tank-cleaning-up-to-1000-litres",
                    "short_description": "Overhead water tank cleaning for tanks up to 1000 litres.",
                    "description": "Cleaning package for accessible overhead tanks up to 1000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Tank repair\nPlumbing work\nChemical treatment beyond standard cleaning",
                    "important_notes": "Safe access and water availability are required.",
                    "base_price": Decimal("779.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 90,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 29,
                },
                {
                    "category": "cleaning",
                    "name": "Overhead Water Tank Cleaning - 1000 to 3000 Litres",
                    "slug": "overhead-water-tank-cleaning-1000-to-3000-litres",
                    "short_description": "Overhead water tank cleaning for 1000 to 3000 litre tanks.",
                    "description": "Cleaning package for accessible overhead tanks from 1000 to 3000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Tank repair\nPlumbing work\nChemical treatment beyond standard cleaning",
                    "important_notes": "Safe access and water availability are required.",
                    "base_price": Decimal("1049.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 120,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 30,
                },
                {
                    "category": "cleaning",
                    "name": "Overhead Water Tank Cleaning - 3000 to 6000 Litres",
                    "slug": "overhead-water-tank-cleaning-3000-to-6000-litres",
                    "short_description": "Overhead water tank cleaning for 3000 to 6000 litre tanks.",
                    "description": "Cleaning package for accessible overhead tanks from 3000 to 6000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Tank repair\nPlumbing work\nChemical treatment beyond standard cleaning",
                    "important_notes": "Safe access and water availability are required.",
                    "base_price": Decimal("1449.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 150,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 31,
                },
                {
                    "category": "cleaning",
                    "name": "Overhead Water Tank Cleaning - 6000 to 10000 Litres",
                    "slug": "overhead-water-tank-cleaning-6000-to-10000-litres",
                    "short_description": "Overhead water tank cleaning for 6000 to 10000 litre tanks.",
                    "description": "Cleaning package for accessible overhead tanks from 6000 to 10000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Tank repair\nPlumbing work\nChemical treatment beyond standard cleaning",
                    "important_notes": "Safe access and water availability are required.",
                    "base_price": Decimal("2499.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 180,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 32,
                },
                {
                    "category": "cleaning",
                    "name": "Overhead Concrete Water Tank Cleaning - Up to 1000 Litres",
                    "slug": "overhead-concrete-water-tank-cleaning-up-to-1000-litres",
                    "short_description": "Concrete overhead tank cleaning for tanks up to 1000 litres.",
                    "description": "Cleaning package for accessible concrete overhead tanks up to 1000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Tank repair\nPlumbing work\nChemical treatment beyond standard cleaning",
                    "important_notes": "Safe access and water availability are required.",
                    "base_price": Decimal("1199.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 120,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 33,
                },
                {
                    "category": "cleaning",
                    "name": "Overhead Concrete Water Tank Cleaning - 1000 to 3000 Litres",
                    "slug": "overhead-concrete-water-tank-cleaning-1000-to-3000-litres",
                    "short_description": "Concrete overhead tank cleaning for 1000 to 3000 litre tanks.",
                    "description": "Cleaning package for accessible concrete overhead tanks from 1000 to 3000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Tank repair\nPlumbing work\nChemical treatment beyond standard cleaning",
                    "important_notes": "Safe access and water availability are required.",
                    "base_price": Decimal("1499.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 150,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 34,
                },
                {
                    "category": "cleaning",
                    "name": "Underground Sump Cleaning - Up to 5000 Litres",
                    "slug": "underground-sump-cleaning-up-to-5000-litres",
                    "short_description": "Underground sump cleaning for sumps up to 5000 litres.",
                    "description": "Cleaning package for accessible underground sumps up to 5000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Sump repair\nMotor or plumbing work\nHigh-risk confined-space work",
                    "important_notes": "Safe access and water disposal path are required.",
                    "base_price": Decimal("1399.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 150,
                    "is_featured": True,
                    "is_popular": True,
                    "display_order": 35,
                },
                {
                    "category": "cleaning",
                    "name": "Underground Sump Cleaning - 5000 to 8000 Litres",
                    "slug": "underground-sump-cleaning-5000-to-8000-litres",
                    "short_description": "Underground sump cleaning for 5000 to 8000 litre sumps.",
                    "description": "Cleaning package for accessible underground sumps from 5000 to 8000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Sump repair\nMotor or plumbing work\nHigh-risk confined-space work",
                    "important_notes": "Safe access and water disposal path are required.",
                    "base_price": Decimal("1899.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 180,
                    "is_featured": False,
                    "is_popular": True,
                    "display_order": 36,
                },
                {
                    "category": "cleaning",
                    "name": "Underground Sump Cleaning - 8000 to 12000 Litres",
                    "slug": "underground-sump-cleaning-8000-to-12000-litres",
                    "short_description": "Underground sump cleaning for 8000 to 12000 litre sumps.",
                    "description": "Cleaning package for accessible underground sumps from 8000 to 12000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Sump repair\nMotor or plumbing work\nHigh-risk confined-space work",
                    "important_notes": "Safe access and water disposal path are required.",
                    "base_price": Decimal("2349.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 210,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 37,
                },
                {
                    "category": "cleaning",
                    "name": "Underground Sump Cleaning - 12000 to 20000 Litres",
                    "slug": "underground-sump-cleaning-12000-to-20000-litres",
                    "short_description": "Underground sump cleaning for 12000 to 20000 litre sumps.",
                    "description": "Cleaning package for accessible underground sumps from 12000 to 20000 litres.",
                    "whats_included": "Draining support\nScrubbing\nSludge removal\nRinse",
                    "whats_excluded": "Sump repair\nMotor or plumbing work\nHigh-risk confined-space work",
                    "important_notes": "Safe access and water disposal path are required.",
                    "base_price": Decimal("3899.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 240,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 38,
                },
                {
                    "category": "home-maintenance",
                    "name": "Mosquito Net Inspection Charge",
                    "slug": "mosquito-net-inspection-charge",
                    "short_description": "Inspection visit for mosquito net measurement, repair, or replacement estimate.",
                    "description": "Inspection visit for mosquito net needs including measurement, repair feasibility, and estimate.",
                    "whats_included": "Technician visit\nMeasurement guidance\nRepair or replacement estimate",
                    "whats_excluded": "Net material\nFrame material\nInstallation charges beyond inspection",
                    "important_notes": "Final price depends on window size, frame type, and material.",
                    "base_price": Decimal("300.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 45,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 39,
                },
                {
                    "category": "home-maintenance",
                    "name": "Sofa Repair Inspection Charge",
                    "slug": "sofa-repair-inspection-charge",
                    "short_description": "Inspection visit for sofa repair scope, material requirement, and estimate.",
                    "description": "Technician visit to inspect sofa damage, repair scope, fabric or foam needs, and final estimate.",
                    "whats_included": "Technician visit\nDamage inspection\nRepair estimate\nMaterial guidance",
                    "whats_excluded": "Fabric, foam, wood, spring, or other materials\nWorkshop transport",
                    "important_notes": "Final repair cost depends on sofa condition and selected material.",
                    "base_price": Decimal("300.00"),
                    "selling_price": None,
                    "advance_amount": Decimal("100.00"),
                    "estimated_duration_minutes": 45,
                    "is_featured": False,
                    "is_popular": False,
                    "display_order": 40,
                },
            ]
        )

        for service in service_data:
            Service.objects.update_or_create(
                slug=service["slug"],
                defaults={
                    **service,
                    "category": categories[service["category"]],
                    "is_active": True,
                },
            )

        core_category_data = [
            ("ac-services", "AC", "AC repair, cleaning, installation, uninstallation and gas services.", 1),
            ("washing-machine-services", "Washing Machine", "Washing machine repair, installation and uninstallation.", 2),
            ("refrigerator-services", "Refrigerator", "Refrigerator inspection, installation and uninstallation.", 3),
        ]
        core_categories = {}
        for slug, name, description, order in core_category_data:
            category, _ = ServiceCategory.objects.update_or_create(
                slug=slug,
                defaults={
                    "name": name,
                    "description": description,
                    "display_order": order,
                    "is_active": True,
                },
            )
            core_categories[slug] = category

        core_services = [
            ("ac-service", "AC Repairs", "ac-services", "Repair & Services", "AC issue diagnosis and repair estimate.", "Issue diagnosis\nBasic inspection\nRepair estimate before work", "499.00", 1),
            ("foam-jet-ac-service", "AC Foam Jet Clean", "ac-services", "Repair & Services", "Foam jet cleaning for accessible AC parts.", "Filter cleaning\nFoam jet coil cleaning\nDrainage and cooling check", "999.00", 2),
            ("full-ac-chemical-wash", "AC Chemical Wash", "ac-services", "Repair & Services", "Deep chemical cleaning for reduced airflow.", "Indoor unit chemical cleaning\nFilter and drain tray wash\nCooling test", "2499.00", 3),
            ("ac-repair-gas-refill", "AC Gas Refill", "ac-services", "Gas Refill", "Cooling diagnosis and gas refill after approval.", "Cooling diagnosis\nLeakage check guidance\nGas refill\nPerformance test", "2799.00", 4),
            ("ac-installation", "AC Installation", "ac-services", "Install & Uninstall", "Standard split AC installation and testing.", "Indoor unit mounting\nConnection and drainage check\nCooling test", "1899.00", 5),
            ("ac-uninstallation", "AC Uninstallation", "ac-services", "Install & Uninstall", "Safe AC disconnection and removal.", "Gas lock where possible\nIndoor and outdoor unit removal\nBasic handover", "999.00", 6),
            ("washing-machine-repair-service", "Washing Machine Repair", "washing-machine-services", "Repair & Services", "Diagnosis for washing, spinning and draining issues.", "Issue diagnosis\nBasic inspection\nRepair estimate before work", "449.00", 1),
            ("washing-machine-installation", "Washing Machine Installation", "washing-machine-services", "Install & Uninstall", "Install and test a compatible washing machine.", "Machine placement\nInlet and drain connection\nBasic function test", "599.00", 2),
            ("washing-machine-uninstallation", "Washing Machine Uninstallation", "washing-machine-services", "Install & Uninstall", "Disconnect and prepare a washing machine for shifting.", "Water inlet disconnection\nDrain disconnection\nSafe handover", "499.00", 3),
            ("refrigerator-repair-services", "Refrigerator Inspection", "refrigerator-services", "Repair & Services", "Inspection for cooling, leakage, noise and electrical issues.", "Issue diagnosis\nBasic external inspection\nRepair estimate before work", "499.00", 1),
            ("refrigerator-installation-uninstallation", "Refrigerator Installation / Uninstallation", "refrigerator-services", "Install & Uninstall", "Position, connect or safely disconnect a refrigerator.", "Placement guidance\nPower and leveling check\nBasic cooling test or safe disconnection", "699.00", 2),
        ]
        core_service_ids = []
        for slug, name, category_slug, group, short, included, price, order in core_services:
            service, created = Service.objects.get_or_create(
                slug=slug,
                defaults={
                    "category": core_categories[category_slug],
                    "name": name,
                    "short_description": short,
                    "description": short,
                    "whats_included": included,
                    "base_price": Decimal(price),
                    "selling_price": None,
                    "advance_amount": Decimal("99.00"),
                    "advance_payment_type": "FIXED",
                    "advance_payment_value": Decimal("99.00"),
                    "estimated_duration_minutes": 60,
                    "is_active": True,
                    "display_order": order,
                    "landing_group": group,
                },
            )
            if not created:
                service.category = core_categories[category_slug]
                service.name = name
                service.landing_group = group
                service.display_order = order
                service.is_active = True
                if not service.short_description:
                    service.short_description = short
                if not service.whats_included:
                    service.whats_included = included
                service.save(
                    update_fields=[
                        "category",
                        "name",
                        "landing_group",
                        "display_order",
                        "is_active",
                        "short_description",
                        "whats_included",
                        "updated_at",
                    ]
                )
            core_service_ids.append(service.id)

        for area in ServiceArea.objects.filter(is_active=True).iterator():
            area.services.add(*core_service_ids)

        active_service_slugs = {service["slug"] for service in service_data} | {item[0] for item in core_services}
        Service.objects.filter(
            slug__in=[
                "triming",
                "ac-deep-cleaning",
                "ac-general-service",
                "ac-not-cooling-repair",
                "ac-water-leakage-repair",
                "ac-installation-standard",
                "ac-uninstallation",
                "ac-gas-refill",
                "ac-inspection-visit",
            ],
        ).exclude(slug__in=active_service_slugs).update(is_active=False)
        ServiceCategory.objects.filter(
            slug__in=["laan-cleaning", "ac-service", "ac-repair", "ac-installation", "gas-refill", "inspection"],
        ).exclude(slug__in=categories.keys()).update(is_active=False)

        self.stdout.write(self.style.SUCCESS("Seeded catalogue data."))
