from decimal import Decimal

from django.core.management.base import BaseCommand

from apps.catalogue.models import Service, ServiceCategory


class Command(BaseCommand):
    help = "Seed development service categories and Purple Squad services."

    def handle(self, *args, **options):
        category_data = [
            {
                "name": "Home Appliances Repair",
                "slug": "home-appliances-repair",
                "description": "Repair, servicing, installation, and maintenance for essential home appliances.",
                "display_order": 1,
            },
            {
                "name": "Cleaning",
                "slug": "cleaning",
                "description": "Home, bathroom, tank, and chimney cleaning services for healthier spaces.",
                "display_order": 2,
            },
        ]
        categories = {}
        for item in category_data:
            category, _ = ServiceCategory.objects.update_or_create(
                slug=item["slug"],
                defaults={
                    "name": item["name"],
                    "description": item["description"],
                    "display_order": item["display_order"],
                    "is_active": True,
                },
            )
            categories[item["slug"]] = category

        included_repair = "Technician visit\nIssue diagnosis\nBasic external inspection\nService estimate before extra work"
        excluded_repair = "Spare parts\nMajor component replacement\nCivil, plumbing, or electrical line work\nBrand warranty handling"
        repair_note = "Final repair cost depends on appliance condition and required parts. Technician confirms extra charges before work starts."

        service_data = [
            {
                "category": "home-appliances-repair",
                "name": "AC Service",
                "slug": "ac-service",
                "short_description": "AC cleaning, cooling check, and routine maintenance for better airflow.",
                "description": "A professional AC service visit for split or window AC units. The technician cleans accessible parts, checks airflow, reviews drainage, and identifies repair or gas-refill needs if present.",
                "whats_included": "Filter cleaning\nIndoor unit inspection\nOutdoor unit visual check\nDrainage check\nBasic cooling test",
                "whats_excluded": "Gas refill\nSpare parts\nDeep jet cleaning\nCompressor, PCB, or motor repair",
                "important_notes": "Power and safe access to indoor and outdoor units are required.",
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("499.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 1,
            },
            {
                "category": "home-appliances-repair",
                "name": "Washing Machine Repair & Service",
                "slug": "washing-machine-repair-service",
                "short_description": "Diagnosis and service for washing, spinning, draining, and noise issues.",
                "description": "Service for semi-automatic, top-load, and front-load washing machines with problems such as water not draining, drum noise, vibration, or cycle failure.",
                "whats_included": included_repair,
                "whats_excluded": excluded_repair,
                "important_notes": repair_note,
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 2,
            },
            {
                "category": "home-appliances-repair",
                "name": "Refrigerator Repair & Services",
                "slug": "refrigerator-repair-services",
                "short_description": "Cooling, leakage, noise, and compressor-related refrigerator inspection.",
                "description": "Technician diagnosis for refrigerators that are not cooling, over-cooling, leaking water, making noise, or showing electrical faults.",
                "whats_included": included_repair,
                "whats_excluded": excluded_repair,
                "important_notes": repair_note,
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("499.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 3,
            },
            {
                "category": "home-appliances-repair",
                "name": "TV Repair & Services",
                "slug": "tv-repair-services",
                "short_description": "TV display, sound, power, and connectivity issue diagnosis.",
                "description": "Inspection and service estimate for LED, LCD, and smart TVs facing no display, no sound, power, remote, or input issues.",
                "whats_included": included_repair,
                "whats_excluded": "Panel replacement\nMotherboard or speaker parts\nWall mount bracket\nBrand warranty handling",
                "important_notes": repair_note,
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": True,
                "display_order": 4,
            },
            {
                "category": "home-appliances-repair",
                "name": "Geyser Repair & Services",
                "slug": "geyser-repair-services",
                "short_description": "Geyser heating, leakage, wiring, thermostat, and servicing support.",
                "description": "Technician visit for electric geyser problems such as no heating, slow heating, leakage, tripping, or unusual noise.",
                "whats_included": included_repair,
                "whats_excluded": "Heating element or thermostat parts\nPlumbing changes\nWall drilling\nElectrical line repair",
                "important_notes": "Water and power supply must be available for testing.",
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": False,
                "display_order": 5,
            },
            {
                "category": "home-appliances-repair",
                "name": "Water Purifier Repair & Services",
                "slug": "water-purifier-repair-services",
                "short_description": "RO/UV purifier service for leakage, low flow, taste, and filter issues.",
                "description": "Repair and maintenance visit for water purifiers with slow water flow, leakage, bad taste, filter alerts, or power issues.",
                "whats_included": included_repair,
                "whats_excluded": "Filters, membrane, pump, UV lamp, or other parts\nPlumbing changes\nWater quality lab testing",
                "important_notes": "Filter or membrane replacement is quoted separately after inspection.",
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": True,
                "display_order": 6,
            },
            {
                "category": "home-appliances-repair",
                "name": "Microwave Oven Repair & Services",
                "slug": "microwave-oven-repair-services",
                "short_description": "Microwave heating, plate rotation, spark, and power issue diagnosis.",
                "description": "Technician visit for microwave ovens with heating failure, turntable issues, sparking, buttons not working, or power faults.",
                "whats_included": included_repair,
                "whats_excluded": "Magnetron, diode, capacitor, fuse, panel, or door parts\nInternal deep cleaning",
                "important_notes": repair_note,
                "base_price": Decimal("599.00"),
                "selling_price": Decimal("449.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": False,
                "is_popular": False,
                "display_order": 7,
            },
            {
                "category": "home-appliances-repair",
                "name": "Dishwasher Repair & Service",
                "slug": "dishwasher-repair-service",
                "short_description": "Dishwasher drainage, cleaning, water inlet, and noise issue diagnosis.",
                "description": "Service visit for dishwashers with poor cleaning, water not draining, water inlet errors, unusual noise, or cycle interruptions.",
                "whats_included": included_repair,
                "whats_excluded": "Pump, motor, sensor, spray arm, or control-board parts\nPlumbing or cabinet modifications",
                "important_notes": repair_note,
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("549.00"),
                "advance_amount": Decimal("199.00"),
                "estimated_duration_minutes": 75,
                "is_featured": False,
                "is_popular": False,
                "display_order": 8,
            },
            {
                "category": "home-appliances-repair",
                "name": "TV Wall Mount Installation",
                "slug": "tv-wall-mount-installation",
                "short_description": "Secure TV wall mounting with alignment and basic setup.",
                "description": "Installation service for mounting a TV on a suitable wall, aligning the bracket, and checking viewing position and cable access.",
                "whats_included": "Wall mount installation\nTV mounting and alignment\nBasic safety check\nCable position guidance",
                "whats_excluded": "Wall mount bracket\nConcealed wiring\nElectrical socket work\nCivil repair or reinforcement",
                "important_notes": "Customer should provide a compatible wall mount bracket unless arranged separately.",
                "base_price": Decimal("799.00"),
                "selling_price": Decimal("599.00"),
                "advance_amount": Decimal("199.00"),
                "estimated_duration_minutes": 75,
                "is_featured": False,
                "is_popular": True,
                "display_order": 9,
            },
            {
                "category": "home-appliances-repair",
                "name": "CCTV Cameras Repair and Installation",
                "slug": "cctv-cameras-repair-installation",
                "short_description": "CCTV camera setup, connection checks, and repair inspection.",
                "description": "Technician visit for CCTV installation or troubleshooting camera, DVR/NVR, power, display, or cable connectivity issues.",
                "whats_included": "Camera point inspection\nBasic installation or repair estimate\nDVR/NVR connection check\nLive-view guidance",
                "whats_excluded": "Cameras, DVR/NVR, hard disk, cable, adapter, or networking equipment\nHigh-ladder or concealed wiring work",
                "important_notes": "Final cost depends on number of camera points and material required.",
                "base_price": Decimal("999.00"),
                "selling_price": Decimal("799.00"),
                "advance_amount": Decimal("249.00"),
                "estimated_duration_minutes": 90,
                "is_featured": False,
                "is_popular": False,
                "display_order": 10,
            },
            {
                "category": "cleaning",
                "name": "Chimney Cleaning & Services",
                "slug": "chimney-cleaning-services",
                "short_description": "Kitchen chimney filter, hood, and grease cleaning service.",
                "description": "Cleaning service for kitchen chimneys affected by grease, smoke residue, and reduced suction. Helps improve airflow and kitchen hygiene.",
                "whats_included": "Filter cleaning\nHood surface cleaning\nAccessible grease removal\nBasic suction check",
                "whats_excluded": "Motor repair\nDuct replacement\nSpare parts\nDeep duct dismantling",
                "important_notes": "Heavy grease buildup may need additional time or repeat cleaning.",
                "base_price": Decimal("899.00"),
                "selling_price": Decimal("699.00"),
                "advance_amount": Decimal("199.00"),
                "estimated_duration_minutes": 75,
                "is_featured": True,
                "is_popular": True,
                "display_order": 1,
            },
            {
                "category": "cleaning",
                "name": "Full House Cleaning",
                "slug": "full-house-cleaning",
                "short_description": "Complete home cleaning for floors, surfaces, rooms, and common areas.",
                "description": "A full-house cleaning visit for occupied homes that need deep dusting, floor cleaning, bathroom touch-up, kitchen surface cleaning, and room-wise hygiene care.",
                "whats_included": "Room dusting\nFloor cleaning\nKitchen exterior surface cleaning\nBathroom touch-up\nCommon area cleaning",
                "whats_excluded": "Pest control\nInterior cabinet cleaning\nSofa or mattress shampooing\nPaint or renovation cleanup",
                "important_notes": "Exact scope and duration depend on home size and condition.",
                "base_price": Decimal("2499.00"),
                "selling_price": Decimal("1999.00"),
                "advance_amount": Decimal("499.00"),
                "estimated_duration_minutes": 240,
                "is_featured": True,
                "is_popular": True,
                "display_order": 2,
            },
            {
                "category": "cleaning",
                "name": "Bathroom Cleaning",
                "slug": "bathroom-cleaning",
                "short_description": "Bathroom tile, floor, mirror, tap, and fixture cleaning.",
                "description": "Bathroom cleaning service focused on stains, scale, floor dirt, mirror marks, fixture buildup, and overall freshness.",
                "whats_included": "Floor and wall tile cleaning\nTap and fixture cleaning\nMirror cleaning\nCommode and basin cleaning\nBasic deodorizing",
                "whats_excluded": "Plumbing repair\nGrout replacement\nSevere hard-water restoration\nPest control",
                "important_notes": "Very old stains may lighten but may not disappear completely in one visit.",
                "base_price": Decimal("699.00"),
                "selling_price": Decimal("499.00"),
                "advance_amount": Decimal("149.00"),
                "estimated_duration_minutes": 60,
                "is_featured": True,
                "is_popular": True,
                "display_order": 3,
            },
            {
                "category": "cleaning",
                "name": "Water Tank Cleaning",
                "slug": "water-tank-cleaning",
                "short_description": "Overhead or sump tank cleaning for sediment and hygiene buildup.",
                "description": "Water tank cleaning service to remove settled dirt, slime, and visible buildup from accessible domestic water tanks.",
                "whats_included": "Tank draining support\nManual scrubbing\nSludge removal\nRinse and basic hygiene check",
                "whats_excluded": "Tank repair\nPlumbing repair\nChemical treatment beyond standard cleaning\nHigh-risk access work",
                "important_notes": "Customer must provide safe tank access and water/power availability.",
                "base_price": Decimal("1299.00"),
                "selling_price": Decimal("999.00"),
                "advance_amount": Decimal("249.00"),
                "estimated_duration_minutes": 120,
                "is_featured": False,
                "is_popular": True,
                "display_order": 4,
            },
        ]

        for service in service_data:
            Service.objects.update_or_create(
                slug=service["slug"],
                defaults={
                    **service,
                    "category": categories[service["category"]],
                    "is_active": True,
                },
            )

        active_service_slugs = {service["slug"] for service in service_data}
        Service.objects.filter(
            slug__in=[
                "triming",
                "ac-deep-cleaning",
                "ac-general-service",
                "ac-not-cooling-repair",
                "ac-water-leakage-repair",
                "ac-installation-standard",
                "ac-uninstallation",
                "ac-gas-refill",
                "ac-inspection-visit",
            ],
        ).exclude(slug__in=active_service_slugs).update(is_active=False)
        ServiceCategory.objects.filter(
            slug__in=["laan-cleaning", "ac-service", "ac-repair", "ac-installation", "gas-refill", "inspection"],
        ).exclude(slug__in=categories.keys()).update(is_active=False)

        self.stdout.write(self.style.SUCCESS("Seeded catalogue data."))
