# Generated by Django 5.2.17 on 2026-08-20 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('RAZORPAY', 'Razorpay')], default='RAZORPAY', max_length=32)),
                ('provider_order_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_type', models.CharField(choices=[('BOOKING_ADVANCE', 'Booking advance'), ('BALANCE', 'Balance'), ('REFUND', 'Refund')], max_length=32)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=32)),
                ('signature_verified', models.BooleanField(default=False)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['booking', 'payment_type', 'status'], name='payments_pa_booking_7858dd_idx'), models.Index(fields=['provider_order_id'], name='payments_pa_provide_c37514_idx'), models.Index(fields=['provider_payment_id'], name='payments_pa_provide_adf74c_idx'), models.Index(fields=['idempotency_key'], name='payments_pa_idempot_d55485_idx')],
            },
        ),
    ]
