# Generated by Django 5.2.17 on 2026-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('OFFLINE', 'Offline')], default='RAZORPAY', max_length=32),
        ),
    ]
