# Generated by Django 5.2.17 on 2026-09-14 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def resolve_existing_payment_duplicates(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    active_statuses = ["CREATED", "PENDING", "SUCCESS"]
    booking_ids = (
        Payment.objects.filter(payment_type="BOOKING_ADVANCE", status__in=active_statuses)
        .values_list("booking_id", flat=True)
        .distinct()
    )
    for booking_id in booking_ids:
        rows = list(
            Payment.objects.filter(
                booking_id=booking_id,
                payment_type="BOOKING_ADVANCE",
                status__in=active_statuses,
            ).order_by("-status", "-created_at")
        )
        for duplicate in rows[1:]:
            duplicate.status = "FAILED"
            duplicate.save(update_fields=["status"])

    keys = (
        Payment.objects.exclude(idempotency_key="")
        .values_list("booking_id", "payment_type", "idempotency_key")
        .distinct()
    )
    for booking_id, payment_type, key in keys:
        duplicates = list(
            Payment.objects.filter(
                booking_id=booking_id,
                payment_type=payment_type,
                idempotency_key=key,
            ).order_by("-created_at")
        )
        for duplicate in duplicates[1:]:
            duplicate.idempotency_key = ""
            duplicate.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_checkoutrequest'),
        ('payments', '0002_alter_payment_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('event', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='parent_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_refund_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(resolve_existing_payment_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_type', 'BOOKING_ADVANCE'), ('status__in', ['CREATED', 'PENDING', 'SUCCESS'])), fields=('booking', 'payment_type'), name='unique_active_booking_advance'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('booking', 'payment_type', 'idempotency_key'), name='unique_payment_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_0b23d5_idx'),
        ),
    ]
