# Generated by Django 5.2.17 on 2026-09-12 11:37

from django.db import migrations, models


def preserve_existing_service_coverage(apps, schema_editor):
    ServiceArea = apps.get_model("locations", "ServiceArea")
    Service = apps.get_model("catalogue", "Service")
    service_ids = list(Service.objects.filter(is_active=True).values_list("id", flat=True))
    for service_area in ServiceArea.objects.all().iterator():
        service_area.services.add(*service_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_servicecategory_image'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_areas', to='catalogue.service'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='services_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_existing_service_coverage, migrations.RunPython.noop),
    ]
