# Generated by Django 5.2.17 on 2026-10-04 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_deactivate_non_launch_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreaLocality',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='locations.servicearea')),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'indexes': [models.Index(fields=['service_area', 'is_active'], name='locations_s_service_cfebea_idx'), models.Index(fields=['slug'], name='locations_s_slug_9bc76c_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_area', 'slug'), name='unique_service_area_locality_slug')],
            },
        ),
    ]
