# Generated by Django 5.2.17 on 2026-08-20 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('category__display_order', 'display_order', 'name')},
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='catalogue_s_is_acti_fddeb0_idx',
        ),
        migrations.AddField(
            model_name='service',
            name='advance_payment_type',
            field=models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=16),
        ),
        migrations.AddField(
            model_name='service',
            name='advance_payment_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='services/covers/'),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='important_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='whats_excluded',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='whats_included',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'is_featured', 'display_order'], name='catalogue_s_is_acti_4850c2_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'is_popular'], name='catalogue_s_is_acti_fb3bcc_idx'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.service'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['service', 'is_active', 'display_order'], name='catalogue_s_service_554f85_idx'),
        ),
    ]
