# Generated by Django 5.2.17 on 2026-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_serviceimage_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
    ]
