# Generated by Django 5.2.17 on 2026-09-18 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_servicecategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('maximum_usage_limit', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='catalogue.service')),
            ],
            options={
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(related_name='packages', through='catalogue.PackageItem', to='catalogue.service'),
        ),
        migrations.AddIndex(
            model_name='packageitem',
            index=models.Index(fields=['package', 'display_order'], name='catalogue_p_package_9b5d95_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageitem',
            constraint=models.UniqueConstraint(fields=('package', 'service'), name='unique_package_service'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='catalogue_p_is_acti_4fe9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['slug'], name='catalogue_p_slug_27ecad_idx'),
        ),
    ]
