# Generated by Django 5.2.17 on 2026-09-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_package_packageitem_package_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='training_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='training_fee_per_unit',
            field=models.BooleanField(default=False),
        ),
    ]
