# Generated by Django 5.2.17 on 2026-09-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_service_training_fee_service_training_fee_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='landing_group',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
