# Generated by Django 5.2.17 on 2026-10-04 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_service_popup_content_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoLandingPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_slug', models.SlugField(max_length=180)),
                ('service_name', models.CharField(max_length=150)),
                ('category_slug', models.SlugField(max_length=180)),
                ('city', models.CharField(default='Chennai', max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('area_slug', models.SlugField(blank=True, max_length=180)),
                ('page_slug', models.CharField(editable=False, max_length=380, unique=True)),
                ('meta_title', models.CharField(max_length=180)),
                ('meta_description', models.CharField(max_length=320)),
                ('h1', models.CharField(max_length=180)),
                ('intro_content', models.TextField()),
                ('pricing_intro', models.TextField(blank=True)),
                ('coverage_areas', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_indexable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('service_slug', 'area_slug'),
                'indexes': [models.Index(fields=['is_active', 'is_indexable'], name='catalogue_s_is_acti_e6d94d_idx'), models.Index(fields=['service_slug', 'area_slug'], name='catalogue_s_service_74f181_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_slug', 'area_slug'), name='unique_seo_service_area_page')],
            },
        ),
    ]
