# Generated by Django 5.2.17 on 2026-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_seed_initial_seo_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='seolandingpage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
