# Generated by Django 5.2.17 on 2026-10-04 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_add_seo_page_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seolandingpage',
            name='canonical_override',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='seolandingpage',
            name='include_in_sitemap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seolandingpage',
            name='page_type',
            field=models.CharField(choices=[('SERVICE_CITY', 'Service + city'), ('SERVICE_AREA', 'Service + area')], default='SERVICE_CITY', max_length=20),
        ),
        migrations.AddField(
            model_name='seolandingpage',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
