# Generated by Django 5.2.17 on 2026-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_add_seo_publication_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='seolandingpage',
            name='featured_services',
            field=models.ManyToManyField(blank=True, related_name='seo_landing_pages', to='catalogue.service'),
        ),
    ]
