# Generated by Django 5.2.17 on 2026-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_seed_all_chennai_seo_area_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='seolandingpage',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('NEEDS_REVIEW', 'Needs editorial review'), ('READY', 'Ready for publication')], default='NEEDS_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='seolandingpage',
            name='primary_keyword',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='seolandingpage',
            name='search_intent',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='seolandingpage',
            name='secondary_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='seolandingpage',
            name='supporting_terms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
