# Generated by Django 5.2.17 on 2026-08-20 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='locations.servicearea')),
            ],
            options={
                'ordering': ('date', 'start_time'),
                'indexes': [models.Index(fields=['service_area', 'date', 'is_active'], name='scheduling__service_ea9f57_idx'), models.Index(fields=['date', 'start_time'], name='scheduling__date_7d213a_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_area', 'date', 'start_time', 'end_time'), name='unique_service_area_slot_time')],
            },
        ),
    ]
