# Generated by Django 5.2.17 on 2026-09-16 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_servicearea_services'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleClosure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closure_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('BLACKOUT', 'Blackout'), ('EMERGENCY', 'Emergency closure')], default='BLACKOUT', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service_area', models.ForeignKey(blank=True, help_text='Leave empty to close every service area.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_closures', to='locations.servicearea')),
            ],
            options={
                'ordering': ('start_date', 'service_area__name'),
                'indexes': [models.Index(fields=['start_date', 'end_date', 'is_active'], name='scheduling__start_d_059285_idx')],
            },
        ),
    ]
