# Generated by Django 5.2.17 on 2026-08-29 08:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalogue', '0002_serviceimage_alter_service_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('desktop_image', models.ImageField(upload_to='banners/desktop/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('mobile_image', models.ImageField(blank=True, upload_to='banners/mobile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('image_alt_text', models.CharField(max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('placement', models.CharField(choices=[('MAIN', 'Main banner'), ('PROMOTIONAL_CAROUSEL', 'Promotional carousel'), ('CATEGORY', 'Category banner'), ('SERVICE_PAGE', 'Service-page banner')], default='MAIN', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('placement', 'display_order', '-created_at'),
                'indexes': [models.Index(fields=['placement', 'is_active', 'display_order'], name='operations__placeme_fbfd1d_idx'), models.Index(fields=['starts_at', 'ends_at'], name='operations__starts__afb817_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('primary_mobile', models.CharField(max_length=16)),
                ('alternate_mobile', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('package', models.CharField(blank=True, max_length=180)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('source', models.CharField(choices=[('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('CALLBACK_REQUEST', 'Callback request'), ('ABANDONED_BOOKING', 'Abandoned booking'), ('PAYMENT_PENDING', 'Payment pending'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='MANUAL', max_length=32)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('FOLLOW_UP', 'Follow-up'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('CLOSED', 'Closed')], default='NEW', max_length=32)),
                ('preferred_callback_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('required_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalogue.service')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('FOLLOW_UP', 'Follow-up'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('CLOSED', 'Closed')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.lead')),
            ],
            options={
                'verbose_name_plural': 'lead status histories',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('package', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='catalogue.servicecategory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='catalogue.service')),
            ],
            options={
                'ordering': ('display_order', 'question'),
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='operations__is_acti_bfe313_idx'), models.Index(fields=['category', 'service'], name='operations__categor_11275d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('question', 'category', 'service'), name='unique_active_faq_context')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['primary_mobile'], name='operations__primary_c5b5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'status'], name='operations__source_9a6b85_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'follow_up_at'], name='operations__status_73106a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['pincode'], name='operations__pincode_eb59bc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='operations__created_c56a59_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstatushistory',
            index=models.Index(fields=['lead', 'created_at'], name='operations__lead_id_f6b4f8_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstatushistory',
            index=models.Index(fields=['to_status'], name='operations__to_stat_3369a8_idx'),
        ),
    ]
