# Generated by Django 5.2.17 on 2026-09-05 08:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalogue', '0003_servicecategory_image'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SERVICE_VIEWED', 'Service viewed'), ('ADDED_TO_CART', 'Added to cart'), ('CHECKOUT_STARTED', 'Checkout started'), ('BOOKING_CREATED', 'Booking created'), ('PAYMENT_LINK_CREATED', 'Payment link created'), ('PAYMENT_LINK_SENT', 'Payment link sent'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('STATUS_CHANGED', 'Status changed'), ('CALL_COMPLETED', 'Call completed'), ('NOTE_ADDED', 'Note added'), ('LEAD_ASSIGNED', 'Lead assigned'), ('LEAD_MERGED', 'Lead merged'), ('MANUAL_PAYMENT_RECORDED', 'Manual payment recorded')], max_length=48)),
                ('previous_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'lead activities',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='funnel_status',
            field=models.CharField(choices=[('VISITED', 'Visited'), ('CART_ADDED', 'Cart added'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('LOST', 'Lost')], default='VISITED', max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_temperature',
            field=models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], default='WARM', max_length=8),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_link_provider_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('LINK_SENT', 'Link sent'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='NOT_REQUIRED', max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_slot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='quoted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('SERVICE_VIEW', 'Service view'), ('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('ADMIN', 'Admin'), ('PHONE_CALL', 'Phone call'), ('CAMPAIGN', 'Campaign'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('CALLBACK_REQUEST', 'Callback request'), ('ABANDONED_BOOKING', 'Abandoned booking'), ('PAYMENT_PENDING', 'Payment pending'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='MANUAL', max_length=32),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['customer', 'required_service', 'funnel_status'], name='operations__custome_73a24a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['funnel_status'], name='operations__funnel__6853d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['payment_status'], name='operations__payment_dd4466_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='operations__source_d84ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_staff'], name='operations__assigne_20989a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['follow_up_at'], name='operations__follow__eae2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_activity_at'], name='operations__last_ac_d596e7_idx'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operations.lead'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', 'created_at'], name='operations__lead_id_0b2218_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['action', 'created_at'], name='operations__action_53ca54_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['performed_by', 'created_at'], name='operations__perform_09242c_idx'),
        ),
    ]
