# Generated by Django 5.2.17 on 2026-09-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingnumbersequence_booking_quantity_and_more'),
        ('operations', '0002_leadactivity_lead_admin_notes_lead_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pending_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_source_lead', to='bookings.booking'),
        ),
    ]
