# Generated by Django 5.2.17 on 2026-09-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_lead_pending_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('CONSUMER_APP', 'Consumer app'), ('ONCALL', 'On-call'), ('SERVICE_VIEW', 'Service view'), ('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('ADMIN', 'Admin'), ('PHONE_CALL', 'Phone call'), ('CAMPAIGN', 'Campaign'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('CALLBACK_REQUEST', 'Callback request'), ('ABANDONED_BOOKING', 'Abandoned booking'), ('PAYMENT_PENDING', 'Payment pending'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='MANUAL', max_length=32),
        ),
    ]
