# Generated by Django 5.2.17 on 2026-08-20 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ADMIN_BOOKING_START', 'Admin booking start'), ('ADMIN_BOOKING_COMPLETE', 'Admin booking complete'), ('ADMIN_BOOKING_CANCEL', 'Admin booking cancel'), ('ADMIN_RECORD_BALANCE', 'Admin record balance'), ('TECHNICIAN_ASSIGN', 'Technician assign'), ('PAYMENT_WEBHOOK_RECEIVED', 'Payment webhook received'), ('PAYMENT_WEBHOOK_REJECTED', 'Payment webhook rejected'), ('PERMISSION_DENIED', 'Permission denied')], max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['request_id'], name='audit_audit_request_06fe30_idx')],
            },
        ),
    ]
