# Generated by Django 5.2.17 on 2026-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ADMIN_BOOKING_START', 'Admin booking start'), ('ADMIN_BOOKING_COMPLETE', 'Admin booking complete'), ('ADMIN_BOOKING_CANCEL', 'Admin booking cancel'), ('ADMIN_RECORD_BALANCE', 'Admin record balance'), ('TECHNICIAN_ASSIGN', 'Technician assign'), ('PAYMENT_WEBHOOK_RECEIVED', 'Payment webhook received'), ('PAYMENT_WEBHOOK_REJECTED', 'Payment webhook rejected'), ('PERMISSION_DENIED', 'Permission denied'), ('SERVICE_CREATED', 'Service created'), ('SERVICE_UPDATED', 'Service updated'), ('SERVICE_DEACTIVATED', 'Service deactivated'), ('SERVICE_PRICE_CHANGED', 'Service price changed'), ('SERVICE_IMAGE_CHANGED', 'Service image changed'), ('CATEGORY_CREATED', 'Category created'), ('CATEGORY_UPDATED', 'Category updated'), ('CATEGORY_DEACTIVATED', 'Category deactivated'), ('LEAD_CREATED', 'Lead created'), ('LEAD_UPDATED', 'Lead updated'), ('LEAD_STATUS_CHANGED', 'Lead status changed'), ('LEAD_CONVERTED', 'Lead converted'), ('BANNER_CREATED', 'Banner created'), ('BANNER_UPDATED', 'Banner updated'), ('BANNER_PUBLICATION_CHANGED', 'Banner publication changed'), ('FAQ_CREATED', 'FAQ created'), ('FAQ_UPDATED', 'FAQ updated')], max_length=64),
        ),
    ]
