# Generated by Django 5.2.17 on 2026-08-20 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('locations', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(max_length=32, unique=True)),
                ('address_snapshot', models.JSONField()),
                ('service_date', models.DateField()),
                ('problem_description', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('PAYMENT_FAILED', 'Payment failed'), ('CONFIRMED', 'Confirmed'), ('TECHNICIAN_ASSIGNED', 'Technician assigned'), ('TECHNICIAN_EN_ROUTE', 'Technician en route'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=32)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=32)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='locations.address')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalogue.service')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.timeslot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'booking status histories',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status'], name='bookings_bo_booking_9deb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_date'], name='bookings_bo_service_304252_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer'], name='bookings_bo_custome_4b90f2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['assigned_technician'], name='bookings_bo_assigne_b174a9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'booking_status'], name='bookings_bo_custome_0e317c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['time_slot', 'booking_status'], name='bookings_bo_time_sl_21f505_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_1d3d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['to_status'], name='bookings_bo_to_stat_7da2b9_idx'),
        ),
    ]
