# Generated by Django 5.2.17 on 2026-09-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_checkoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=4, unique=True)),
                ('current_serial', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='training_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('PAYMENT_FAILED', 'Payment failed'), ('CONFIRMED', 'Confirmed'), ('TECHNICIAN_ASSIGNED', 'Technician assigned'), ('TECHNICIAN_EN_ROUTE', 'Technician en route'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=32),
        ),
    ]
