# Generated by Django 5.2.17 on 2026-08-20 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking confirmed'), ('TECHNICIAN_ASSIGNED', 'Technician assigned'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('SERVICE_COMPLETED', 'Service completed')], max_length=32)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['booking', 'event'], name='notificatio_booking_fac438_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx'), models.Index(fields=['channel', 'event'], name='notificatio_channel_025df7_idx')],
            },
        ),
    ]
