# Generated by Django 5.2.17 on 2026-08-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-app'), ('PUSH', 'Push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('BOOKING_RECEIVED', 'Booking received'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_SUCCESSFUL', 'Payment successful'), ('BOOKING_CONFIRMED', 'Booking confirmed'), ('BOOKING_RESCHEDULED', 'Booking rescheduled'), ('TECHNICIAN_ASSIGNED', 'Technician assigned'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('SERVICE_COMPLETED', 'Service completed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16),
        ),
    ]
