# Generated by Django 5.2.17 on 2026-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_send_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('BOOKING_RECEIVED', 'Booking received'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_SUCCESSFUL', 'Payment successful'), ('BOOKING_CONFIRMED', 'Booking confirmed'), ('BOOKING_RESCHEDULED', 'Booking rescheduled'), ('TECHNICIAN_ASSIGNED', 'Technician assigned'), ('TECHNICIAN_CHANGED', 'Technician changed'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('TECHNICIAN_EN_ROUTE', 'Technician en route'), ('TECHNICIAN_ARRIVED', 'Technician arrived'), ('SERVICE_STARTED', 'Service started'), ('SERVICE_COMPLETED', 'Service completed'), ('BALANCE_PAYMENT_PENDING', 'Balance payment pending'), ('BALANCE_PAYMENT_SUCCESSFUL', 'Balance payment successful'), ('REFUND_INITIATED', 'Refund initiated'), ('REFUND_COMPLETED', 'Refund completed'), ('REVIEW_REQUEST', 'Review request')], max_length=32),
        ),
    ]
